# Data Cleaning

In [21]:
# Import libraries
import pandas as pd
import numpy as np
from google.colab import files

In [22]:
# Read data file
df = pd.read_csv('lighting_data.csv')

# Display data
df

,light_id,location_name,fault_type,timestamp,severity_level,fault_status,maintenance_cost
0,L0602,Chinatown,Power-related,2020-01-06 06:34:34,Informational,Resolved,435.43
1,L0616,Bishan,Power-related,2020-01-06 09:20:51,Informational,Acknowledged,456.65
2,L0199,Bugis Junction,Power-related,2020-01-06 19:45:33,Critical,Closed,336.82
3,L0036,Chinatown,Power-related,2020-01-07 10:49:23,High,Resolved,368.61
4,L0259,Pasir Ris,Power-related,2020-01-08 16:49:23,Critical,Closed,179.93
...,...,...,...,...,...,...,...
189,L0718,Pasir Ris,Control system,2020-12-27 07:38:39,Critical,Resolved,482.28
190,L0539,Bugis Junction,Communication,2020-12-28 03:03:47,Informational,Detected,183.64
191,L0281,Outram Park,Power-related,2020-12-28 03:22:38,High,Closed,380.25
192,L0169,Bishan,Environmental,2020-12-28 07:31:05,Critical,Detected,308.93
193,L0738,Toa Payoh,Environmental,2020-12-30 01:05:55,High,Resolved,350.29

In [23]:
# Dataset(rows, columns)
df.shape

(194, 7)

In [24]:
# Display first five data
df.head()

,light_id,location_name,fault_type,timestamp,severity_level,fault_status,maintenance_cost
0,L0602,Chinatown,Power-related,2020-01-06 06:34:34,Informational,Resolved,435.43
1,L0616,Bishan,Power-related,2020-01-06 09:20:51,Informational,Acknowledged,456.65
2,L0199,Bugis Junction,Power-related,2020-01-06 19:45:33,Critical,Closed,336.82
3,L0036,Chinatown,Power-related,2020-01-07 10:49:23,High,Resolved,368.61
4,L0259,Pasir Ris,Power-related,2020-01-08 16:49:23,Critical,Closed,179.93

In [25]:
# Display last five data
df.tail()

,light_id,location_name,fault_type,timestamp,severity_level,fault_status,maintenance_cost
189,L0718,Pasir Ris,Control system,2020-12-27 07:38:39,Critical,Resolved,482.28
190,L0539,Bugis Junction,Communication,2020-12-28 03:03:47,Informational,Detected,183.64
191,L0281,Outram Park,Power-related,2020-12-28 03:22:38,High,Closed,380.25
192,L0169,Bishan,Environmental,2020-12-28 07:31:05,Critical,Detected,308.93
193,L0738,Toa Payoh,Environmental,2020-12-30 01:05:55,High,Resolved,350.29

In [26]:
# Display summary
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   light_id          194 non-null    object
 1   location_name     194 non-null    object
 2   fault_type        194 non-null    object
 3   timestamp         194 non-null    object
 4   severity_level    194 non-null    object
 5   fault_status      194 non-null    object
 6   maintenance_cost  170 non-null    float64
dtypes: float64(1), object(6)
memory usage: 10.7+ KB

In [27]:
# Find missing values
missing_count = df.isnull().sum()
missing_count

light_id             0
location_name        0
fault_type           0
timestamp            0
severity_level       0
fault_status         0
maintenance_cost    24
dtype: int64

The maintenance_cost column has 18 missing values.

In [28]:
# Find percentage of missing values
missing_count = df.isna().sum()
total_rows = len(df)
missing_proportion = (missing_count / total_rows) * 100

# Sort descending
missing_proportion = missing_proportion.round(2).sort_values(ascending=False)
print(missing_proportion)

maintenance_cost    12.37
location_name        0.00
light_id             0.00
fault_type           0.00
timestamp            0.00
severity_level       0.00
fault_status         0.00
dtype: float64

Since the maintenance cost is a numeric column and may contain outliers, the median is used to fill its missing values.

In [29]:
# Find median of maintenance_cost column
median_value = df['maintenance_cost'].median()
median_rounded = round(median_value, 2)
print("Median value:", median_rounded)

Median value: 272.35

In [30]:
# Fill missing values with median
df['maintenance_cost'].fillna(median_value, inplace=True)

/tmp/ipykernel_760/2732969241.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['maintenance_cost'].fillna(median_value, inplace=True)

In [31]:
# Check duplicate rows
num_duplicates = df.duplicated().sum()
print(f"Duplicate rows: {num_duplicates}")

Duplicate rows: 0

In [32]:
# Verify filling to ensure no null values
print(df['maintenance_cost'].isnull().sum())

0

In [33]:
# Convert timestamps to pandas datetime
df['timestamp'] = pd.to_datetime(df['timestamp'])

# Sort by timestamp
df = df.sort_values('timestamp').reset_index(drop=True)

In [34]:
# Verify data type
print(df['timestamp'].dtype)

datetime64[ns]

In [35]:
# Verify sort
is_sorted = df['timestamp'].equals(df['timestamp'].sort_values())
print("Is sorted:", is_sorted)

Is sorted: True

In [36]:
# Standardise categorical values
df['fault_type'] = df['fault_type'].str.strip().str.title()
df['severity_level'] = df['severity_level'].str.strip().str.title()
df['fault_status'] = df['fault_status'].str.strip().str.title()
df['location_name'] = df['location_name'].str.strip().str.title()

In [37]:
# Extract time features
df['year'] = df['timestamp'].dt.year
df['month'] = df['timestamp'].dt.month
df['day'] = df['timestamp'].dt.day
df['day_of_week'] = df['timestamp'].dt.day_name()
df['hour'] = df['timestamp'].dt.hour

In [38]:
filename='lighting_data_cleaned.csv'

# Save to csv and download
df.to_csv(filename, index=False) # Save csv
files.download(filename) # Automatically download the file in colab

# Read final dataset
df

,light_id,location_name,fault_type,timestamp,severity_level,fault_status,maintenance_cost,year,month,day,day_of_week,hour
0,L0602,Chinatown,Power-Related,2020-01-06 06:34:34,Informational,Resolved,435.43,2020,1,6,Monday,6
1,L0616,Bishan,Power-Related,2020-01-06 09:20:51,Informational,Acknowledged,456.65,2020,1,6,Monday,9
2,L0199,Bugis Junction,Power-Related,2020-01-06 19:45:33,Critical,Closed,336.82,2020,1,6,Monday,19
3,L0036,Chinatown,Power-Related,2020-01-07 10:49:23,High,Resolved,368.61,2020,1,7,Tuesday,10
4,L0259,Pasir Ris,Power-Related,2020-01-08 16:49:23,Critical,Closed,179.93,2020,1,8,Wednesday,16
...,...,...,...,...,...,...,...,...,...,...,...,...
189,L0718,Pasir Ris,Control System,2020-12-27 07:38:39,Critical,Resolved,482.28,2020,12,27,Sunday,7
190,L0539,Bugis Junction,Communication,2020-12-28 03:03:47,Informational,Detected,183.64,2020,12,28,Monday,3
191,L0281,Outram Park,Power-Related,2020-12-28 03:22:38,High,Closed,380.25,2020,12,28,Monday,3
192,L0169,Bishan,Environmental,2020-12-28 07:31:05,Critical,Detected,308.93,2020,12,28,Monday,7
193,L0738,Toa Payoh,Environmental,2020-12-30 01:05:55,High,Resolved,350.29,2020,12,30,Wednesday,1